backend:
  name: github
  repo: TU_USUARIO/chinajapon1977
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
