backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

publish_mode: editorial_workflow

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    format: "frontmatter"
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
